import 'package:flutter/material.dart';
import 'notification.dart';
import '../services/notification_text_service.dart';

/// Extension on AppNotification for display-related functionality
extension NotificationDisplay on AppNotification {
  /// Get localized title for this notification
  String getLocalizedTitle(BuildContext context) {
    return NotificationTextService.generateTitle(
      context,
      type,
      entityName: _extractEntityName(),
      actorName: _extractActorName(),
    );
  }

  /// Get localized body text for this notification
  String getLocalizedBody(BuildContext context) {
    return NotificationTextService.generateBody(
      context,
      type,
      entityName: _extractEntityName(),
      actorName: _extractActorName(),
      workspaceName: _extractWorkspaceName(),
      additionalInfo: _extractAdditionalInfo(),
      dueDate: _extractDueDate(),
      eventTime: _extractEventTime(),
    );
  }

  /// Get icon for this notification
  IconData getIcon() {
    return NotificationTextService.getIcon(type);
  }

  /// Get color for this notification
  Color getColor(BuildContext context) {
    return NotificationTextService.getColor(context, type);
  }

  /// Get priority for this notification
  NotificationPriority getPriority() {
    return NotificationTextService.getPriority(type);
  }

  /// Check if notification should use custom text
  bool get shouldUseCustomText {
    // If title and body are already provided, use them
    return title.isNotEmpty && body.isNotEmpty;
  }

  /// Get display title (custom or localized)
  String getDisplayTitle(BuildContext context) {
    if (shouldUseCustomText && title.isNotEmpty) {
      return title;
    }
    return getLocalizedTitle(context);
  }

  /// Get display body (custom or localized)
  String getDisplayBody(BuildContext context) {
    if (shouldUseCustomText && body.isNotEmpty) {
      return body;
    }
    return getLocalizedBody(context);
  }

  // Private helper methods to extract data from notification

  String? _extractEntityName() {
    // Try to extract entity name from body or title
    // This is a placeholder - in a real implementation, you might
    // store this in a separate field or parse it from the data
    return null;
  }

  String? _extractActorName() {
    // Try to extract actor name
    return null;
  }

  String? _extractWorkspaceName() {
    // Try to extract workspace name
    return null;
  }

  String? _extractAdditionalInfo() {
    // Try to extract additional info (like status, role, etc.)
    return null;
  }

  DateTime? _extractDueDate() {
    // Try to extract due date
    return null;
  }

  DateTime? _extractEventTime() {
    // Try to extract event time
    return null;
  }
}

/// Helper class for creating notifications with proper localization
class NotificationBuilder {
  final NotificationType type;
  final String userId;
  final String workspaceId;

  String? entityType;
  String? entityId;
  String? entityName;
  String? actorName;
  String? workspaceName;
  String? additionalInfo;
  DateTime? dueDate;
  DateTime? eventTime;
  String? dedupeKey;

  NotificationBuilder({
    required this.type,
    required this.userId,
    required this.workspaceId,
  });

  NotificationBuilder setEntity({
    required String type,
    required String id,
    String? name,
  }) {
    entityType = type;
    entityId = id;
    entityName = name;
    return this;
  }

  NotificationBuilder setActor(String name) {
    actorName = name;
    return this;
  }

  NotificationBuilder setWorkspaceName(String name) {
    workspaceName = name;
    return this;
  }

  NotificationBuilder setAdditionalInfo(String info) {
    additionalInfo = info;
    return this;
  }

  NotificationBuilder setDueDate(DateTime date) {
    dueDate = date;
    return this;
  }

  NotificationBuilder setEventTime(DateTime time) {
    eventTime = time;
    return this;
  }

  NotificationBuilder setDedupeKey(String key) {
    dedupeKey = key;
    return this;
  }

  /// Build notification with context for localization
  AppNotification build(BuildContext context) {
    final title = NotificationTextService.generateTitle(
      context,
      type,
      entityName: entityName,
      actorName: actorName,
    );

    final body = NotificationTextService.generateBody(
      context,
      type,
      entityName: entityName,
      actorName: actorName,
      workspaceName: workspaceName,
      additionalInfo: additionalInfo,
      dueDate: dueDate,
      eventTime: eventTime,
    );

    final now = DateTime.now();

    return AppNotification(
      id: '', // Will be generated by backend
      userId: userId,
      workspaceId: workspaceId,
      type: type,
      title: title,
      body: body,
      entityType: entityType,
      entityId: entityId,
      dedupeKey: dedupeKey,
      readAt: null,
      pushedAt: null,
      createdAt: now,
      updatedAt: now,
    );
  }

  /// Build notification data for API request
  Map<String, dynamic> buildApiData(BuildContext context) {
    final title = NotificationTextService.generateTitle(
      context,
      type,
      entityName: entityName,
      actorName: actorName,
    );

    final body = NotificationTextService.generateBody(
      context,
      type,
      entityName: entityName,
      actorName: actorName,
      workspaceName: workspaceName,
      additionalInfo: additionalInfo,
      dueDate: dueDate,
      eventTime: eventTime,
    );

    final data = <String, dynamic>{
      'workspaceId': workspaceId,
      'type': type.value,
      'title': title,
      'body': body,
    };

    if (entityType != null) data['entityType'] = entityType;
    if (entityId != null) data['entityId'] = entityId;
    if (dedupeKey != null) data['dedupeKey'] = dedupeKey;

    return data;
  }
}
